////
[[introduction]]
== Introduction


[[what-is-acegi-security]]
=== What is Spring Security?
Spring Security provides comprehensive security services for Java EE-based enterprise software applications. There is a particular emphasis on supporting projects built using The Spring Framework, which is the leading Java EE solution for enterprise software development. If you're not using Spring for developing enterprise applications, we warmly encourage you to take a closer look at it. Some familiarity with Spring - and in particular dependency injection principles - will help you get up to speed with Spring Security more easily.

People use Spring Security for many reasons, 

but most are drawn to the project after finding the security features of Java EE's Servlet Specification or EJB Specification lack the depth required for typical enterprise application scenarios. Whilst mentioning these standards, it's important to recognise that they are not portable at a WAR or EAR level. Therefore, if you switch server environments, it is typically a lot of work to reconfigure your application's security in the new target environment. Using Spring Security overcomes these problems, and also brings you dozens of other useful, customisable security features.

[[what-is-acegi-security]]

As you probably know two major areas of application security are "authentication" and "authorization" (or "access-control"). These are the two main areas that Spring Security targets. "Authentication" is the process of establishing a principal is who they claim to be (a "principal" generally means a user, device or some other system which can perform an action in your application)."Authorization" refers to the process of deciding whether a principal is allowed to perform an action within your application. To arrive at the point where an authorization decision is needed, the identity of the principal has already been established by the authentication process. These concepts are common, and not at all specific to Spring Security.


At an authentication level, Spring Security supports a wide range of authentication models. Most of these authentication models are either provided by third parties, or are developed by relevant standards bodies such as the Internet Engineering Task Force. In addition, Spring Security provides its own set of authentication features. Specifically, Spring Security currently supports authentication integration with all of these technologies:

////

[[introduction]]
== 스프링 시큐리티 소개

[[what-is-acegi-security]]
=== 스프링 시큐리티란 
스프링 시큐리티는 Java EE 기반의 Enterprise 소프트웨어 어플리케이션을 위한 전반적인 보안 솔루션을 제공한다. 특히 스프링 시큐리티는 enterpise 소프트웨어 개발을 위한 선구적인 Java EE 솔루션인 스프링 프레임웍에 기반하여 빌드하는 프로젝트를 지원한다. 만약 어플리케이션을 개발하는데 스프링을 사용하고 있지 않다면 이 가이드를 꼼꼼하게 읽기를 권장한다. 그렇지 않고 스프링과 어느정도 친숙한 사용자라면 - 특히 dependency injection 을 다뤄본 사용자라면 - 보다 쉽게 스프링 시큐리티를 시작할 수 있을 것이다. 

사람들은 제각기 다양한 목적을 갖고 스프링 시큐리티를 사용하는데, 아마도 이 중 대부분은 이미 Java EE 서블렛이나 EJB 스펙이 enterprise 어플리케이션 시나리오에 필요한 보안 기준들을 제대로 충족시키지 못한다는 사실을 발견한 후 여기로 오게 되었을 것이다. 보안 기준을 검토할 때, Java EE 서블렛이나 EJB 스펙은 WAR 혹은 EAR 레벨에 이식되지 않는다는 사실을 알아야만 한다. 이 말인즉슨 당신이 서버 환경을 변경해야 할 때, 변경할 환경에 맞추어 어플리케이션의 보안 설정들도 재설정해야 한다는 것을 뜻한다. 스프링 시큐리티를 사용한다면 이러한 문제들을 극복할 수 있다. 그리고 그에 더하여 그 이상의 유용성과 유연함(customisable)을 제공받을 수 있을 것이다. 

[[what-is-acegi-security]]

어플리케이션 보안에서 가장 중요한 두 가지 키워드는 바로 인증(authentication)와 권한 부여(authorization)다. 이것들은 스프링 시큐리티가 목표로 삼는 주요 영역이기도 하다. 인증(authentication)은 요청에 따라 보안 주체(principal)를 생성하는 프로세스에 대한 것이다.(보안 주체는 일반적으로 사용자, 장치 또는 당신의 어플리케이션에서 어떤 기능을 수행하는 다른 시스템들을 의미한다.) 권한 부여(Authorization)은 어플리케이션 내에서 어떠한 액션을 수행할 때 그것을 허락할 것인지의 여부를 결정하는 프로세스다. 권한 부여 프로세스가 필요한 지점까지 가려면, 보안 주체는 먼저 인증 단계를 거쳐야 한다. 이러한 개념은 일반적인 것으로, 스프링 시큐리티에서만 쓰이는 건 아니다. 

인증 단계에서 스프링 시큐리티는 광범위한 인증 모델을 제시한다. 인증 모델 중 대부분은 third party를 통해 지원이 되거나 IETF 와 같은 국제 기구에 의해 개발된 것이다. 게다가 스프링 시큐리티는 자체적인 인증 유형을 제공한다. 특히 스프링 시큐리티는 현재 아래 열거된 기술들의 인증 통합 또한 지원하고 있다.


* HTTP BASIC authentication headers (an IETF RFC-based standard)

* HTTP Digest authentication headers (an IETF RFC-based standard)

* HTTP X.509 client certificate exchange (an IETF RFC-based standard)

//* LDAP (a very common approach to cross-platform authentication needs, especially in large environments) 
* LDAP (cross-platform 인증 환경에 있어 가장 일반적으로 쓰이는 방식이다. 특히 규모가 큰 시스템에 적합하다.)
//Form-based authentication (for simple user interface needs) 
* Form 기반 인증 (간단한 UI를 통하여 인증되는 방식)
// * OpenID authentication
* OpenID 인증

//* Authentication based on pre-established request headers (such as Computer Associates Siteminder)
* 미리 설정해놓은 request header 값에 기반한 인증 방식 (Computer Associates Siteminder 참고)

//* JA-SIG Central Authentication Service (otherwise known as CAS, which is a popular open source single sign-on system)
* JA-SIG 중앙 인증 서비스 (CAS로 알려져 있으며 꽤 인기 있는 오픈 소스 SSO 시스템이다)

* Transparent authentication context propagation for Remote Method Invocation (RMI) and HttpInvoker (a Spring remoting protocol)

//* Automatic "remember-me" authentication (so you can tick a box to avoid re-authentication for a predetermined period of time)
* 'remember-me' 기능을 이용한 자동 인증(체크박스를 통해 일정 시간 동안 재인증을 방지할 수 있다)

// * Anonymous authentication (allowing every unauthenticated call to automatically assume a particular security identity) 
* 익명 인증 (특정 보안 주체-역주:익명 유저-를 자동으로 지정하여 권한이 필요없는 모든 기능을 수행하도록 함)

//* Run-as authentication (which is useful if one call should proceed with a different security identity)
* Run-as 인증 (다른 보안 주체와 통신해야 할 때 매우 유용하다)

* Java Authentication and Authorization Service (JAAS)

//* JEE container autentication (so you can still use Container Managed Authentication if desired)
JEE container 인증 (원한다면 Container Managed Authentication 을 계속해서 사용할 수 있다)

* Kerberos

* Java Open Source Single Sign On (JOSSO) *

* OpenNMS Network Management Platform *

* AppFuse *

* AndroMDA *

* Mule ESB *

* Direct Web Request (DWR) *

* Grails *

* Tapestry *

* JTrac *

* Jasypt *

* Roller *

* Elastic Path *

* Atlassian Crowd *

* 사용자가 직접 만든 인증 시스템(아래 내용 참고)
//* Your own authentication systems (see below)



(* Denotes provided by a third party
////
Many independent software vendors (ISVs) adopt Spring Security because of this significant choice of flexible authentication models. Doing so allows them to quickly integrate their solutions with whatever their end clients need, without undertaking a lot of engineering or requiring the client to change their environment. If none of the above authentication mechanisms suit your needs, Spring Security is an open platform and it is quite simple to write your own authentication mechanism. Many corporate users of Spring Security need to integrate with "legacy" systems that don't follow any particular security standards, and Spring Security is happy to "play nicely" with such systems.
////
대다수의 독립 소프트웨어 벤더(ISVs)는 스프링 시큐리티가 가진 인증 모델의 유연성에 중점을 두고 스프링 시큐리티를 적용한다. 이렇게 하면 그들과 그들의 고객이 무엇을 필요로 하든, 솔루션에 맞게 환경을 변경하거나 막대한 개발을 하지 않아도 인증 모델과 솔루션을 쉽게 통합할 수 있기 때문이다. 위에 기술한 인증 메카니즘 중 본인의 필요에 맞는 게 하나도 없더라도, 스프링 시큐리티는 오픈 플랫폼이어서 어떤 인증 플랫폼에도 적용하는 것이 매우 간단하다. 스프링 시큐리티의 사용자들 중 상당수는 그 어떤 보안 표준을 따르지 않고 만들어진 "레거시" 시스템과의 통합을 원한다. 그리고 스프링 시큐리티는 그러한 시스템들과 매우 멋지게 공존한다. 
////
Irrespective of the authentication mechanism, Spring Security provides a deep set of authorization capabilities. There are three main areas of interest  - authorizing web requests, authorizing whether methods can be invoked, and authorizing access to individual domain object instances. To help you understand the differences, consider the authorization capabilities found in the Servlet Specification web pattern security, EJB Container Managed Security and file system security respectively. Spring Security provides deep capabilities in all of these important areas, which we'll explore later in this reference guide.
////
어떤 인증 메카니즘을 사용하든지 스프링 시큐리티는 언제나 높은 수준의 권한 부여 기능을 제공한다. 권한 관리에 있어 가장 주요한 세 가지 영역은 Web request 권한 관리, 메소드 호출 시의 권한 관리, 그리고 개별 도메인 객체 접근 권한 관리이다. 이들의 차이점은 아마도 서블렛 web pattern security, EJB 컨테이너 기반 Security, 그리고 파일 시스템 Security 각각 떠올려 보면 쉬울 것이다. 스프링 시큐리티는 이 모든 영역에서 높은 수준의 권한 관리 기능을 제공한다. 앞으로 우리는 그리고 이 레퍼런스 가이드를 통해 이 내용들을 탐험할 것이다.

////
[[history]]
=== History
Spring Security began in late 2003 as "The Acegi Security System for Spring". A question was posed on the Spring Developers' mailing list asking whether there had been any consideration given to a Spring-based security implementation. At the time the Spring community was relatively small (especially compared with the size today!), and indeed Spring itself had only existed as a SourceForge project from early 2003. The response to the question was that it was a worthwhile area, although a lack of time currently prevented its exploration.

With that in mind, a simple security implementation was built and not released. A few weeks later another member of the Spring community inquired about security, and at the time this code was offered to them. Several other requests followed, and by January 2004 around twenty people were using the code. These pioneering users were joined by others who suggested a SourceForge project was in order, which was duly established in March 2004.
////
[[history]]
=== 스프링 시큐리티의 역사 
스프링 시큐리티는 2003년 말에 "The Acegi Security Systme for Spring" 이라는 이름으로 시작되었다. 시작은 Spring 개발자 메일링 리스트에 누군가 스프링 기반의 보안 모듈을 만들지 않겠느냐는 제안을 던지면서부터였다. 그때 스프링 커뮤니티는 매우 작았고(지금 규모에 비해서) 2003년 초까지 SourceForge(역주:최근의 github 과 같은 소스 코드 레파지토리/커뮤니티이다)에서만 존재하고 있었다. 제안에 대한 답변은 탐구해 볼 시간이 부족하긴하지만 일단 해볼만한 가치가 있는 일이라는 것이었다. 

이 제안을 염두에 두어 아주 간단한 보안 모듈이 개발되었지만 릴리즈되지는 않았다. 몇 주가 지난 후 스프링 커뮤니티에 새로운 멤버들이 보안 영역에 참여하게 되었다. 그때 이 코드들은 모두 그들에게 넘어갔다. 이후 몇 가지 요구사항들이 뒤따랐고 2004년 1월에는 약 20여명의 사람들이 이 코드를 사용하게 되었다. 모두 SourceForge 프로젝트에 제안한 사람들로부터 초대된 사람들이었다. 정식으로 설립된 것은 2004년 5월이었다. 


In those early days, the project didn't have any of its own authentication modules. Container Managed Security was relied upon for the authentication process, with Acegi Security instead focusing on authorization. This was suitable at first, but as more and more users requested additional container support, the fundamental limitation of container-specific authentication realm interfaces became clear. There was also a related issue of adding new JARs to the container's classpath, which was a common source of end user confusion and misconfiguration.

Acegi Security-specific authentication services were subsequently introduced. Around a year later, Acegi Security became an official Spring Framework subproject. The 1.0.0 final release was published in May 2006 - after more than two and a half years of active use in numerous production software projects and many hundreds of improvements and community contributions.

Acegi Security became an official Spring Portfolio project towards the end of 2007 and was rebranded as "Spring Security".

Today Spring Security enjoys a strong and active open source community. There are thousands of messages about Spring Security on the support forums. There is an active core of developers who work on the code itself and an active community which also regularly share patches and support their peers.


[[release-numbering]]
=== Release Numbering
It is useful to understand how Spring Security release numbers work, as it will help you identify the effort (or lack thereof) involved in migrating to future releases of the project. Each release uses a standard triplet of integers: MAJOR.MINOR.PATCH. The intent is that MAJOR versions are incompatible, large-scale upgrades of the API. MINOR versions should largely retain source and binary compatibility with older minor versions, thought there may be some design changes and incompatible updates. PATCH level should be perfectly compatible, forwards and backwards, with the possible exception of changes which are to fix bugs and defects.

The extent to which you are affected by changes will depend on how tightly integrated your code is. If you are doing a lot of customization you are more likely to be affected than if you are using a simple namespace configuration.

You should always test your application thoroughly before rolling out a new version.


[[get-spring-security]]
=== Getting Spring Security
You can get hold of Spring Security in several ways. You can download a packaged distribution from the main http://spring.io/spring-security[Spring Security] page, download individual jars from the Maven Central repository (or a Spring Maven repository for snapshot and milestone releases) or, alternatively, you can build the project from source yourself.

[[maven]]
==== Usage with Maven

A minimal Spring Security Maven set of dependencies typically looks like the following:

.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
<!-- ... other dependency elements ... -->
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-web</artifactId>
	<version>{spring-security-version}</version>
</dependency>
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-config</artifactId>
	<version>{spring-security-version}</version>
</dependency>
</dependencies>
----

If you are using additional features like LDAP, OpenID, etc. you will need to also include the appropriate <<modules>>.

[[maven-repositories]]
===== Maven Repositories
All GA releases (i.e. versions ending in .RELEASE) are deployed to Maven Central, so no additional Maven repositories need to be declared in your pom.

If you are using a SNAPSHOT version, you will need to ensure you have the Spring Snapshot repository defined as shown below:

.pom.xml
[source,xml]
----
<repositories>
<!-- ... possibly other repository elements ... -->
<repository>
	<id>spring-snapshot</id>
	<name>Spring Snapshot Repository</name>
	<url>http://repo.spring.io/snapshot</url>
</repository>
</repositories>
----

If you are using a milestone or release candidate version, you will need to ensure you have the Spring Milestone repository defined as shown below:

.pom.xml
[source,xml]
----
<repositories>
<!-- ... possibly other repository elements ... -->
<repository>
	<id>spring-milestone</id>
	<name>Spring Milestone Repository</name>
	<url>http://repo.spring.io/milestone</url>
</repository>
</repositories>
----

[[maven-bom]]
===== Spring Framework Bom

Spring Security builds against Spring Framework {spring-version}, but should work with 4.0.x. The problem that many users will have is that Spring Security's transitive dependencies resolve Spring Framework {spring-version} which can cause strange classpath problems.

One (tedious) way to circumvent this issue would be to include all the Spring Framework modules in a http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management[<dependencyManagement>] section of your pom. An alternative approach is to include the `spring-framework-bom` within your `<dependencyManagement>` section of your `pom.xml` as shown below:

.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-framework-bom</artifactId>
		<version>{spring-version}</version>
		<type>pom</type>
		<scope>import</scope>
	</dependency>
	</dependencies>
</dependencyManagement>
----

This will ensure that all the transitive dependencies of Spring Security use the Spring {spring-version} modules.

NOTE: This approach uses Maven's "bill of materials" (BOM) concept and is only available in Maven 2.0.9+. For additional details about how dependencies are resolved refer to http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven's Introduction to the Dependency Mechanism documentation].

[[gradle]]
==== Gradle
A minimal Spring Security Gradle set of dependencies typically looks like the following:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	compile 'org.springframework.security:spring-security-web:{spring-security-version}'
	compile 'org.springframework.security:spring-security-config:{spring-security-version}'
}
----

If you are using additional features like LDAP, OpenID, etc. you will need to also include the appropriate <<modules>>.

[[gradle-repositories]]
===== Gradle Repositories
All GA releases (i.e. versions ending in .RELEASE) are deployed to Maven Central, so using the mavenCentral() repository is sufficient for GA releases.

.build.gradle
[source,groovy]
----
repositories {
	mavenCentral()
}
----

If you are using a SNAPSHOT version, you will need to ensure you have the Spring Snapshot repository defined as shown below:

.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/snapshot' }
}
----

If you are using a milestone or release candidate version, you will need to ensure you have the Spring Milestone repository defined as shown below:

.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/milestone' }
}
----

[[gradle-resolutionStrategy]]
===== Using Spring 4.0.x and Gradle

By default Gradle will use the newest version when resolving transitive versions. This means that often times no additional work is necessary when running Spring Security {spring-security-version} with Spring Framework {spring-version}. However, at times there can be issues that come up so it is best to mitigate this using http://www.gradle.org/docs/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html[Gradle's ResolutionStrategy] as shown below:

.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
configurations.all {
	resolutionStrategy.eachDependency { DependencyResolveDetails details ->
		if (details.requested.group == 'org.springframework') {
			details.useVersion '{spring-version}'
		}
	}
}
----

This will ensure that all the transitive dependencies of Spring Security use the Spring {spring-version} modules.

NOTE: This example uses Gradle 1.9, but may need modifications to work in future versions of Gradle since this is an incubating feature within Gradle.

[[modules]]
==== Project Modules
In Spring Security 3.0, the codebase has been sub-divided into separate jars which more clearly separate different functionaltiy areas and third-party dependencies. If you are using Maven to build your project, then these are the modules you will add to your `pom.xml`. Even if you're not using Maven, we'd recommend that you consult the `pom.xml` files to get an idea of third-party dependencies and versions. Alternatively, a good idea is to examine the libraries that are included in the sample applications.


[[spring-security-core]]
===== Core - spring-security-core.jar
Contains core authentication and access-contol classes and interfaces, remoting support and basic provisioning APIs. Required by any application which uses Spring Security. Supports standalone applications, remote clients, method (service layer) security and JDBC user provisioning. Contains the top-level packages:

* `org.springframework.security.core`

* `org.springframework.security.access`

* `org.springframework.security.authentication`

* `org.springframework.security.provisioning`





[[spring-security-remoting]]
===== Remoting - spring-security-remoting.jar
Provides intergration with Spring Remoting. You don't need this unless you are writing a remote client which uses Spring Remoting. The main package is `org.springframework.security.remoting`.


[[spring-security-web]]
===== Web - spring-security-web.jar
Contains filters and related web-security infrastructure code. Anything with a servlet API dependency. You'll need it if you require Spring Security web authentication services and URL-based access-control. The main package is `org.springframework.security.web`.


[[spring-security-config]]
===== Config - spring-security-config.jar
Contains the security namespace parsing code & Java configuration code.
You need it if you are using the Spring Security XML namespace for configuration or Spring Security's Java Configuration support.
The main package is `org.springframework.security.config`.
None of the classes are intended for direct use in an application.


[[spring-security-ldap]]
===== LDAP - spring-security-ldap.jar
LDAP authentication and provisioning code. Required if you need to use LDAP authentication or manage LDAP user entries. The top-level package is `org.springframework.security.ldap`.


[[spring-security-acl]]
===== ACL - spring-security-acl.jar
Specialized domain object ACL implementation. Used to apply security to specific domain object instances within your application. The top-level package is `org.springframework.security.acls`.


[[spring-security-cas]]
===== CAS - spring-security-cas.jar
Spring Security's CAS client integration. If you want to use Spring Security web authentication with a CAS single sign-on server. The top-level package is `org.springframework.security.cas`.


[[spring-security-openid]]
===== OpenID - spring-security-openid.jar
OpenID web authentication support. Used to authenticate users against an external OpenID server. `org.springframework.security.openid`. Requires OpenID4Java.


[[get-source]]
==== Checking out the Source
Since Spring Security is an Open Source project, we'd strongly encourage you to check out the source code using git. This will give you full access to all the sample applications and you can build the most up to date version of the project easily. Having the source for a project is also a huge help in debugging. Exception stack traces are no longer obscure black-box issues but you can get straight to the line that's causing the problem and work out what's happening. The source is the ultimate documentation for a project and often the simplest place to find out how something actually works.

To obtain the source for the project, use the following git command:

[source,txt]
----
git clone https://github.com/spring-projects/spring-security.git
----

This will give you access to the entire project history (including all releases and branches) on your local machine.
