[[new]]
== 스프링 시큐리티 4.1 에서 새로운 것들
https://github.com/spring-projects/spring-security/issues?utf8=%E2%9C%93&q=milestone%3A%224.1.0+RC1%22[100개가 넘는 RC1 이슈들]과 https://github.com/spring-projects/spring-security/issues?utf8=%E2%9C%93&q=milestone%3A%224.1.0+RC2%22[60개가 넘는 RC2 이슈들]이 스프링 시큐리티 4.1 에서 고쳐졌습니다.

여기에 개선된 사항들입니다 
////

== What's New in Spring Security 4.1

There were https://github.com/spring-projects/spring-security/issues?utf8=%E2%9C%93&q=milestone%3A%224.1.0+RC1%22[100+ RC1 issues] and https://github.com/spring-projects/spring-security/issues?utf8=%E2%9C%93&q=milestone%3A%224.1.0+RC2%22[60+ RC2 issues] fixed in Spring Security 4.1.

Here is the list of improvements:
////

=== 자바 설정 향상
* <<jc-authentication-userdetailsservice,자바설정을 통해 간소화된 UserDetailsService>>
* <<jc-authentication-authenticationprovider,자바 설정을 통해 간소화된 AuthenticationProvider >>
*  `LogoutConfigurer`를 통해 설정 가능한 콘텐츠 협상 `LogoutSuccessHandler`
* `SessionManagementConfigurer`를 통해 설정가능한  `InvalidSessionStrategy` 
* `HttpSecurity.addFilterAt`를 사용하여서 특정 위치의 체인에 필터 추가하기

////
=== Java Configuration Improvements
* <<jc-authentication-userdetailsservice,Simplified UserDetailsService Java Configuration>>
* <<jc-authentication-authenticationprovider,Simplified AuthenticationProvider Java Configuration>>
* Configurable Content Negotiating `LogoutSuccessHandler`(s) via `LogoutConfigurer`
* Configurable `InvalidSessionStrategy` via `SessionManagementConfigurer`
* Ability to add a `Filter` at a specific location in the chain using `HttpSecurity.addFilterAt`
////

=== 웹 어플리케이션 보안 향상
* <<headers-csp, 콘텐츠 보안 방침(CSP)>>
* <<headers-hpkp, HTTP public Key pinning (HPKP)>>
* <<csrf-cookie,CookieCsrfTokenRepository>> 를 제공하여서 간단한 앵귤러JS와 CSRF통합을 이룸
* 추가된 `ForwardAuthenticationFailureHandler` & `ForwardAuthenticationSuccessHandler`


=== Web Application Security Improvements
* <<headers-csp,Content Security Policy (CSP)>>
* <<headers-hpkp,HTTP Public Key Pinning (HPKP)>>
* <<csrf-cookie,CookieCsrfTokenRepository>> provides simple AngularJS & CSRF integration
* Added `ForwardAuthenticationFailureHandler` & `ForwardAuthenticationSuccessHandler`
* <<mvc-authentication-principal,AuthenticationPrincipal>> supports expression attribute to support transforming the `Authentication.getPrincipal()` object (i.e. handling immutable custom `User` domain objects)

=== Authorization Improvements
* <<el-access-web-path-variables,Path Variables in Web Security Expressions>>
* <<method-security-meta-annotations,Method Security Meta Annotations>>

=== Crypto Module Improvements
* SCrypt support with `SCryptPasswordEncoder`
* PBKDF2 support with <<spring-security-crypto-passwordencoders,Pbkdf2PasswordEncoder>>
* New `BytesEncryptor` implementation for BouncyCastle using _AES/CBC/PKCS5Padding_ and _AES/GCM/NoPadding_ algorithms

=== Testing Improvements
* <<test-method-withanonymoususer,@WithAnonymousUser>>
* <<test-method-withuserdetails,@WithUserDetails>> allows specifying the `UserDetailsService` bean name
* <<test-method-meta-annotations,Test Meta Annotations>>
* Ability to mock a list of `GrantedAuthority` using `SecurityMockMvcResultMatchers.withAuthorities`

=== General Improvements
* Re-organization of sample projects
* Moved to GitHub issues
