[[overall-architecture]]

////
= Architecture and Implementation

Once you are familiar with setting up and running some namespace-configuration based applications, you may wish to develop more of an understanding of how the framework actually works behind the namespace facade. Like most software, Spring Security has certain central interfaces, classes and conceptual abstractions that are commonly used throughout the framework. In this part of the reference guide we will look at some of these and see how they work together to support authentication and access-control within Spring Security.
////

== 아키텍쳐와 구현체

당신이 어플리케이션에 기반한 네임스페이스 설정을 세팅하고 실행해보는 것이 한번 익숙해진다면, 당신은 아마 네임스페이스 파사드 뒤에서 어떻게 프레임워크가 동작하는지 좀 더 이해하고 싶을 것입니다. 다른 대부분의 소프트웨어와 마찬가지로 스프링 시큐리티는 특정 주요 인터페이스, 클래스와 핵십추상화 층이 있어서 프레임워크 전반적으로 사용되고 있습니다. 레퍼런스 가이드의 이번 장에서는 이것들의 일부를 살펴보고, 어떻게 이것들이 서로 작동하여 스프링 시큐리티 내에서 인증과 접근제어를 지원하는 지 알아보도록 하겠습니다. 

//====

include::03-07-technical-overview.adoc[]

include::03-08-core-services.adoc[]

//====
