////
[[preface]]
= Preface
Spring Security provides a comprehensive security solution for Java EE-based enterprise software applications. As you will discover as you venture through this reference guide, we have tried to provide you a useful and highly configurable security system.

Security is an ever-moving target, and it's important to pursue a comprehensive, system-wide approach. In security circles we encourage you to adopt "layers of security", so that each layer tries to be as secure as possible in its own right, with successive layers providing additional security. The "tighter" the security of each layer, the more robust and safe your application will be. At the bottom level you'll need to deal with issues such as transport security and system identification, in order to mitigate man-in-the-middle attacks. Next you'll generally utilise firewalls, perhaps with VPNs or IP security to ensure only authorised systems can attempt to connect. In corporate environments you may deploy a DMZ to separate public-facing servers from backend database and application servers. Your operating system will also play a critical part, addressing issues such as running processes as non-privileged users and maximising file system security. An operating system will usually also be configured with its own firewall. Hopefully somewhere along the way you'll be trying to prevent denial of service and brute force attacks against the system. An intrusion detection system will also be especially useful for monitoring and responding to attacks, with such systems able to take protective action such as blocking offending TCP/IP addresses in real-time. Moving to the higher layers, your Java Virtual Machine will hopefully be configured to minimize the permissions granted to different Java types, and then your application will add its own problem domain-specific security configuration. Spring Security makes this latter area - application security - much easier.

Of course, you will need to properly address all security layers mentioned above, together with managerial factors that encompass every layer. A non-exhaustive list of such managerial factors would include security bulletin monitoring, patching, personnel vetting, audits, change control, engineering management systems, data backup, disaster recovery, performance benchmarking, load monitoring, centralised logging, incident response procedures etc.

With Spring Security being focused on helping you with the enterprise application security layer, you will find that there are as many different requirements as there are business problem domains. A banking application has different needs from an ecommerce application. An ecommerce application has different needs from a corporate sales force automation tool. These custom requirements make application security interesting, challenging and rewarding.

Please read <<getting-started>>, in its entirety to begin with. This will introduce you to the framework and the namespace-based configuration system with which you can get up and running quite quickly. To get more of an understanding of how Spring Security works, and some of the classes you might need to use, you should then read <<overall-architecture>>. The remaining parts of this guide are structured in a more traditional reference style, designed to be read on an as-required basis. We'd also recommend that you read up as much as possible on application security issues in general. Spring Security is not a panacea which will solve all security issues. It is important that the application is designed with security in mind from the start. Attempting to retrofit it is not a good idea. In particular, if you are building a web application, you should be aware of the many potential vulnerabilities such as cross-site scripting, request-forgery and session-hijacking which you should be taking into account from the start. The OWASP web site (http://www.owasp.org/) maintains a top ten list of web application vulnerabilities as well as a lot of useful reference information.

We hope that you find this reference guide useful, and we welcome your feedback and <<jira,suggestions>>.

Finally, welcome to the Spring Security <<community,community>>.
////

[[서론]]
= 서론

스프링 시큐리티는 Java EE Enterprise 소프트웨어 어플리케이션을 위한 통합 보안 솔루션을 제공한다. 이 레퍼런스 가이드를 읽으며 당신이 스프링 시큐리티에 대해 알아가는 만큼, 스프링 시큐리티 역시 당신에게 더 큰 유용성과 유연함(Configurable)을 선사할 것이다.

보안은 누구에게나 영원한 숙제다. 보안을 위해서는 시스템 전반적인 접근과 통합적인 해결책을 추구하는 것이 중요하다. 보안 업계에서는 "layers of security" 의 도입을 권장한다. "layers of security"란 각각의 레이어들이 일단 그들 기능에 맞는 최대한의 보안성을 확보하고, 또 추가적으로 보안을 제공하는 레이어를 갖추는 것을 뜻한다. 개별 레이어의 보안성이 철저해질 수록 어플리케이션은 더욱 탄탄하고 안전해질 수 있다. 일단 "layers of security"의 가장 밑단을 보자. 여기에서는 일단 MITM(man-in-the-middle attacks,*역주:예컨대 인증 토큰을 중간에서 가로채 정보를 취득하는 공격) 가능성을 줄일 수 있도록 transport security 나 System Identification 과 같은 문제를 다루어야 한다. 그 다음엔 권한이 있는 시스템들만 연결할 수 있도록 방화벽이나 VPN, IP 보안들을 활용할 것이다. 협업 환경이라면 일반 사용자들이 접근하는 웹 서버를 뒷단의 데이터베이스 서버나 어플리케이션 서버와 분리하여 DMZ존에 Deploy 하도록 설계할 것이다. OS 레벨에서는 non-privileged user로 프로세스를 실행하거나 파일 시스템 보안을 최대화하는 것과 같이 크리티컬한 이슈들을 다룬다. 아마도 당신은 서비스 거부 공격을 방지하거나 시스템에 대한 과부하 공격을 대비하기 위해 이러한 일련의 과정을 수행할 것이다. IDS(침입 탐지 시스템) 또한 공격을 탐지하는 툴인데, 여기에 공격자의 TCP/IP 주소를 차단하는 등 실제적인 방어 액션을 취할 수 있는 시스템(IPS)을 갖추는 편이 더욱 유용하다. 이제 최상위 레이어를 살펴보자. 여기에서는 JVM이 자바 타입마다 퍼미션을 부여하여 권한을 최소화하도록 설정할 수 있다. 그리고나서 이제 당신의 어플리케이션이 어플리케이션 영역의 보안 문제를 위해 여러 보안 설정을 추가할 것이다. 스프링 시큐리티는 이 중 가장 마지막 영역인 어플리케이션 보안을 더욱 쉽게 구축할 수 있도록 도와줄 것이다.

물론 보안을 위해서는 위에 언급된 모든 보안 레이어들을 전체적으로 적절히 고려해야 한다. 그 뿐 아니라 이 모든 레이어를 아우르는 관리적 요소 또한 함께 고민해야 한다. 러프하게 짚어보자면 일단 관리적 요소에는 모니터링, 패치, 임직원 인사 검증(personnel vetting), 감사, 관리 시스템 구축, 데이터 백업, 재난 복구, 퍼포먼스 벤치마킹, load monitoring, 로그 서버 구축(centralized logging), 재난 대책 등이 속한다.

스프링 시큐리티는 enterprise 어플리케이션 보안 레이어에 초점을 맞추어 당신을 도울 것이다. 프로젝트를 진행하면서 당신은 비즈니스 영역의 문제 만큼이나 시스템 요구 사항도 많고 다양하다는 것을 알게 될 것이다. 예컨대 은행 어플리케이션의 시스템 요구사항은 이커머스 어플리케이션과 다르고, 이커머스 어플리케이션 역시 영업 자동화 솔루션과는 다른 시스템 요구 사항을 가질 것이다. 이렇게 만나게 될 다양한 요구사항들은 어플리케이션 보안에 새로운 도전을 주고, 흥미를 유발하며, 또 그에 적합한 보상을 선사한다.

먼저 스프링 시큐리티를 시작하기 위해 link:https://github.com/ksug/spring-security-reference-translation/tree/master/book/02-getting-started[Chapter 1. 시작하기 에 대해 먼저 읽기를 권한다. 이 챕터에서는 프레임웍과 namespace 기반 설정 시스템을 소개한다. namespace 기반 설정은 스프링 시큐리티를 모르는 사람도 빨리 익숙해질 수 있게 돕는다. 또한 스프링 시큐리티 어떻게 작동하는 지 알고 싶거나 당신이 사용하는 데에 있어 필요한 몇몇 클래스들을 이해하고 싶다면 [Part 2. 아키텍처와 구현체들]을 읽어야 한다. 이 가이드의 남은 파트들은 읽기 편한 전통적인 레퍼런스 스타일로 작성되어 있다. 무엇보다도 우리는 당신에게 어플리케이션 보안 이슈를 가능한 많이 찾아 읽을 것을 권장한다. 스프링 시큐리티는 모든 보안 이슈를 해결하는 만병통치약이 결코 아니다. 보안은 어플리케이션 시작 단계부터 보안에 대해 잘 구상하는 것이 무엇보다도 중요하다. 일단 만든 이후에 개선하려는 건 좋은 생각이 아니다. 특히, 만약 웹 어플리케이션을 새로 구축한다면, Cross-site 스크립팅, Request 위조, Session-hijacking 등에 대해 미리 숙지하고 고려해야만 한다. OWASP 웹사이트(http://www.owasp.org) 에 방문하면 웹 어플리케이션 보안 결함 top 10 리스트를 확인할 수 있다. 레퍼런스처럼 아주 잘 정리되어 있다.

당신에게 이 레퍼런스 가이드가 유용하기를 바라고, 또한 피드백과 제안에는 언제든 열려 있다!

마지막으로 스프링 시큐리티 커뮤니티에 첫 발을 내디신 것을 진심으로 환영한다.